name: codecards
description: Code Cards
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^2.0.3
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  flutter_svg: ^0.17.4
  http: ^0.12.1
  provider: ^4.1.3
  flutter_bloc: ^3.2.0
  flutter_local_notifications: ^1.4.4
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.1
  url_launcher: ^5.4.11
  uni_links: ^0.4.0
  shared_preferences: ^0.5.7+3
  admob_flutter: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Nunito Black
      fonts:
        - asset: fonts/Nunito-Black.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
