name: codecards
description: Code Cards
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^2.0.3
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  flutter_svg: ^0.17.4
  http: ^0.12.1
  provider: ^4.1.3
  flutter_bloc: ^3.2.0
  flutter_local_notifications: ^1.4.4
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.1
  url_launcher: ^5.4.11
  uni_links: ^0.4.0
  shared_preferences: ^0.5.7+3
  admob_flutter: ^0.3.4
  vibration: ^1.4.0
  image_picker: ^0.6.7+2
  flutter_rating_bar: ^3.0.1+1
  dough: ^0.0.5
  simple_animations: ^1.1.3
  page_transition: ^1.1.5
  flutter_webview_plugin: ^0.3.11
  flushbar: ^1.10.4
  path_provider: ^1.6.11
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  rxdart: ^0.23.0
  swipe_stack: ^1.0.0
  carousel_slider: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # hive_generator: ^0.7.0+2
  build_runner: ^1.10.0

dependency_overrides:
  path: ^1.6.4

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Nunito Black
      fonts:
        - asset: fonts/Nunito-Black.ttf
    -  family: Montserrat
       fonts:
         - asset: fonts/Montserrat-Regular.ttf
         - asset: fonts/Montserrat-Bold.ttf
           weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
